### ISSUE TITLE
Bounding box is not moving in dashboard widget

### ISSUE THREAD

**Issue by sesom42** [pluginkollektiv/statify#28] opened 2016-09-23 07:50 UTC
The bounding box does not follow the mouse. On entering the widget the box is displayed on a static position. Tested with FF 49.0 and Chrome 53.0.

![statify box problem ong](https://cloud.githubusercontent.com/assets/8649051/18778032/a04d43e8-8172-11e6-91ad-d7ad366b2d4c.png)

**Comment by websupporter** [comment] 2016-09-23 09:08
It's not just the box, sometimes the text is not in the right direction:
![js-error](https://cloud.githubusercontent.com/assets/6458412/18780369/de5a66ee-8185-11e6-8de3-cf70406f62eb.jpg)

I suspect right now the helper function `popup()`. What I've noticed so far is the `dx` jumps quite a lot. When I get negative values, my text is in the wrong place. But haven't figured out yet, whats going on.

Crossreferencing: https://wordpress.org/support/topic/statistics-displaying-incorrectly/ 
It doesn't look like a conflict between antispam bee and statify, but more a unique js error in the raphael-helper.

**Comment by websupporter** [comment] 2016-09-24 07:15
Hi @sesom42, I've tried to reproduce your specific problem. I did encounter some, but can't reproduce the box not moving to the supposed position. I am testing on FF49 as well. Can you give a more detailed path to how to reproduce it? For example, the problem I encountered above, I can reproduce it when highlighting the same point over and over again. In this case it jumps (not on a regular base though) the way you can see in the screenshot.

When I simply enter the widget with the mouse or try a bit I was not able to reproduce the problem showing in your screenshot.

Thank you.

**Comment by sesom42** [comment] 2016-09-26 21:25
I have tested with all plugins disabled and then the box is displayed correctly. After enabling my plugins step by step I have found the plugin that triggers the issue: Antispam Bee. If the dashboard widget in Antispam Bee is enabled then the box in Statify does not follow the mouse cursor.

**Comment by websupporter** [comment] 2016-09-28 08:25
Thanks @sesom42 for reporting. I've made a pull request which would solve this problem.

**Closed as completed** 2016-10-17 19:36 UTC
