### ISSUE TITLE
statify_cleanup cron event does not work on multisite

### ISSUE THREAD

**Issue by blueclochard** [pluginkollektiv/statify#133] opened 2019-09-19 16:06 UTC
Hello people,

I may have discovered a bug where the statify_cleanup cron event does not work on sites in a multisite installation that are not the main site. The problem of course, is that this can lead to enormous database sizes on websites with a lot of traffic.

The way I understand how the "Period of data saving" option (first option under Configure on the Dashboard widget of Statify) works, is that statify_cleanup deletes all data from before the number of days you set here. This is exactly how it works on the main site in the multisite installation. On other sites in the multisite installation this unfortunately does not work. Data from before the number of days set is not deleted. 

To reproduce this, please:

1. Go to the dashboard widget on any site within a multisite installation that is not the main site. Then set the number of days to something lower than the current setting. For example, change it from 7 to 7. 

2. Run the statify_cleanup event. Normally it runs daily, but for testing purposes it is easier to run it manually than to wait a day.

3. Go back to the Statify widget and change the number of days back to the original number, 7 days in my example. Statistics for all 7 days will reappear. I do not believe this is intended, as everything from before the last 5 days should have been deleted. Alternatively, you can see that the data still persists in the Wordpress database. 

I tried removing and reinstalling the plugin. The cron event is created properly, but for some reason it only seems to work on the main site in the multisite installation.

Would anybody have a solution for this?

Wordpress version: 5.2.3
Statify version: 1.6.3

**Comment by florianbrinkmann** [comment] 2019-11-11 20:32
Hi @blueclochard,

thanks for your bug report, and sorry for the late response! I gave it a try on my own site, that is a multisite with Statify, but was not able to reproduce the issue. Do you have Statify active on a per-site basis in your multisite, or network-activated?

Thanks!
Florian

**Comment by krafit** [comment] 2020-04-12 16:53
Hi @blueclochard I'll close this issue for now, since there has nothing happened here for quite some time.

If you keep running into this problem, please feel free to reopen this issue or get in touch with our via the [support forums](https://wordpress.org/support/plugin/statify/).

**Closed as completed by krafit** 2020-04-12 16:53 UTC
Labels: bug, Needs testing
